ALTER TABLE properties ADD COLUMN IF NOT EXISTS source_subject TEXT;
ALTER TABLE properties ADD COLUMN IF NOT EXISTS source_value TEXT;
ALTER TABLE properties ADD COLUMN IF NOT EXISTS source_rent TEXT;
ALTER TABLE properties ADD COLUMN IF NOT EXISTS source_comps TEXT;
ALTER TABLE properties ADD COLUMN IF NOT EXISTS source_updated_at TIMESTAMPTZ;

ALTER TABLE analyses ADD COLUMN IF NOT EXISTS provider_trace JSONB DEFAULT NULL;
